### PR TITLE
Updated figure, new MPI acronym

### PR DESCRIPTION
**Pull request by kameyer226**
Updated a figure and added an interface barrier which resolves by using a minimal programming interface.   Removed .pdf from .gitignore in order to show the changes, would have to put back later.   Did not remove any references to the original network graphic or .svg file.

### CODE REVIEW

**Comment by untzag** [comment]
My initial reaction---I'm more likely to describe yaq as solving protocol complexity than API complexity. After all, sometimes the interfaces we encapsulate are simpler than the yaq interface. In other words I'm more excited about standardization than minimization.

There is a pattern, especially with data acquisition peripherals, where the yaq interface DOES focus on providing a very opinionated minimal version of the API. Perhaps we should highlight that pattern more in the paper, but I'm not sure that this is the best way of doing it.

Happy to discuss further---wonder what other coauthors think.

**Comment by untzag** [comment]
> The value of this MPI is that it can be formed by wrapping and/or converting the API from its native language into a language known to be transparent to researchers, such as the programming language Python.

How central is this idea of switching languages to your point here, @kameyer226? I wonder if your additions are calling for a greater focus on our usage of Python?

**Comment by kameyer226** [comment]
I recall earlier discussion where we realized yaq doesn't have to rely on python in the future, and like to generalize the yaq project as best as possible.   I do not know how far down the road we go into python specifics for these papers.

**Comment by untzag** [comment]
I think we have a consensus through internal discussion that this MPI idea doesn't fit well into the paper, closing.

**Pull request closed without merging**
